#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File Name : gt.py
'''Purpose : Intro sth                                 '''
# Creation Date : 1427444696
# Last Modified :
# Release By : Doom.zhou


from requests import get
import sys
import json
import re


key = ' '.join(sys.argv[1:])
if re.match(r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$', key):
    url = 'http://ipinfo.io/%s' % key
    r = get(url)
    print(r.text)
    sys.exit(2)
url = 'http://fanyi.youdao.com/openapi.do'
paramater = {
    'keyfrom': 'gohjkl', 'key': '1240450357', 'type': 'data',
    'doctype': 'json', 'version': '1.1', 'q': key,
    }
r = get(url, params=paramater)
try:
    a = json.loads(r.text)['basic']
except:
    a = json.loads(r.text)
print(json.dumps(a, ensure_ascii=False, sort_keys=True, indent=4))
