#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File Name : gt.py
'''Purpose : Intro sth                                 '''
# Creation Date : 1427444696
# Last Modified :
# Release By : Doom.zhou


from requests import get
import sys
import json


key = str(sys.argv[1])
url = 'http://fanyi.youdao.com/openapi.do'
paramater = {
    'keyfrom': 'gohjkl', 'key': '1240450357', 'type': 'data',
    'doctype': 'json', 'version': '1.1', 'q': key,
    }
r = get(url, params=paramater)
a = json.loads(r.text)['basic']
print(json.dumps(a, ensure_ascii=False, sort_keys=True, indent=4))
